"""initial schema

Revision ID: 15b0ae902a91
Revises: 
Create Date: 2026-08-25 19:19:58.463206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b0ae902a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('dataset_seed', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('baseline_recovered_minor', sa.Integer(), nullable=False),
    sa.Column('recoveros_recovered_minor', sa.Integer(), nullable=False),
    sa.Column('baseline_recovery_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recoveros_recovery_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('baseline_unnecessary_actions', sa.Integer(), nullable=False),
    sa.Column('recoveros_unnecessary_actions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('razorpay_account_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_account_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_customer_id', sa.String(length=128), nullable=False),
    sa.Column('contact_email_hash', sa.String(length=128), nullable=True),
    sa.Column('contact_phone_hash', sa.String(length=128), nullable=True),
    sa.Column('historical_successful_payments', sa.Integer(), nullable=False),
    sa.Column('historical_failed_payments', sa.Integer(), nullable=False),
    sa.Column('is_opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_customer_id', name='uq_customer_per_merchant')
    )
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('evaluation_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('synthetic_event_ref', sa.String(length=64), nullable=False),
    sa.Column('ground_truth_recoverable', sa.Boolean(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('baseline_action', sa.String(length=32), nullable=True),
    sa.Column('baseline_recovered', sa.Boolean(), nullable=False),
    sa.Column('recoveros_action', sa.String(length=32), nullable=True),
    sa.Column('recoveros_recovered', sa.Boolean(), nullable=False),
    sa.Column('recoveros_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_events_evaluation_run_id'), 'evaluation_events', ['evaluation_run_id'], unique=False)
    op.create_table('merchant_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('max_retry_attempts', sa.Integer(), nullable=False),
    sa.Column('min_retry_cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('max_communication_attempts', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('max_incentive_percent', sa.Integer(), nullable=False),
    sa.Column('allow_incentives', sa.Boolean(), nullable=False),
    sa.Column('escalation_amount_threshold_minor', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_incentive_percent >= 0 AND max_incentive_percent <= 100', name='ck_incentive_pct_range'),
    sa.CheckConstraint('max_retry_attempts >= 0', name='ck_max_retry_nonneg'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('revenue_risk_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Enum('PAYMENT_FAILURE', 'CHECKOUT_ABANDONMENT', 'RECURRING_PAYMENT_FAILURE', 'MANDATE_FAILURE', 'OVERDUE_INVOICE', name='riskeventtype'), nullable=False),
    sa.Column('failure_reason', sa.Enum('INSUFFICIENT_FUNDS', 'CARD_EXPIRED', 'BANK_TIMEOUT', 'ISSUER_DECLINE', 'NETWORK_ERROR', 'USER_ABANDONED', 'MANDATE_REVOKED', 'UNKNOWN', name='failurereason'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('previous_attempts', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'source_event_id', name='uq_source_event_per_merchant')
    )
    op.create_index(op.f('ix_revenue_risk_events_customer_id'), 'revenue_risk_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_risk_events_merchant_id'), 'revenue_risk_events', ['merchant_id'], unique=False)
    op.create_index('ix_risk_event_ref', 'revenue_risk_events', ['reference_type', 'reference_id'], unique=False)
    op.create_table('recovery_workflows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('risk_event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_state', sa.Enum('DETECTED', 'ENRICHING', 'DIAGNOSING', 'SCORING', 'PLANNING', 'POLICY_CHECK', 'APPROVED', 'EXECUTING', 'VERIFYING', 'PENDING_VERIFICATION', 'RECOVERED', 'ESCALATED', 'EXHAUSTED', 'ABANDONED', 'FAILED', name='workflowstate'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('communication_count', sa.Integer(), nullable=False),
    sa.Column('recovered_amount_minor', sa.Integer(), nullable=False),
    sa.Column('recovery_cost_minor', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['risk_event_id'], ['revenue_risk_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_event_id')
    )
    op.create_index(op.f('ix_recovery_workflows_current_state'), 'recovery_workflows', ['current_state'], unique=False)
    op.create_index(op.f('ix_recovery_workflows_merchant_id'), 'recovery_workflows', ['merchant_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recoverability_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('recommended_action', sa.Enum('RETRY_PAYMENT', 'DELAY_AND_RETRY', 'SEND_PAYMENT_LINK', 'SEND_REMINDER', 'OFFER_INCENTIVE', 'REQUEST_CUSTOMER_ACTION', 'ESCALATE_TO_HUMAN', 'STOP', name='recommendedaction'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('expected_recovery_minor', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('recommended_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('customer_message_intent', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('was_fallback', sa.Boolean(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.CheckConstraint('recoverability_score >= 0 AND recoverability_score <= 1', name='ck_recoverability_range'),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_workflow_id'), 'ai_decisions', ['workflow_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_workflow_id'), 'audit_events', ['workflow_id'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_state', sa.Enum('DETECTED', 'ENRICHING', 'DIAGNOSING', 'SCORING', 'PLANNING', 'POLICY_CHECK', 'APPROVED', 'EXECUTING', 'VERIFYING', 'PENDING_VERIFICATION', 'RECOVERED', 'ESCALATED', 'EXHAUSTED', 'ABANDONED', 'FAILED', name='workflowstate'), nullable=True),
    sa.Column('to_state', sa.Enum('DETECTED', 'ENRICHING', 'DIAGNOSING', 'SCORING', 'PLANNING', 'POLICY_CHECK', 'APPROVED', 'EXECUTING', 'VERIFYING', 'PENDING_VERIFICATION', 'RECOVERED', 'ESCALATED', 'EXHAUSTED', 'ABANDONED', 'FAILED', name='workflowstate'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_transitions_workflow_id'), 'workflow_transitions', ['workflow_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_decision_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_action', sa.Enum('RETRY_PAYMENT', 'DELAY_AND_RETRY', 'SEND_PAYMENT_LINK', 'SEND_REMINDER', 'OFFER_INCENTIVE', 'REQUEST_CUSTOMER_ACTION', 'ESCALATE_TO_HUMAN', 'STOP', name='recommendedaction'), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'BLOCK', 'ESCALATE', name='policydecision'), nullable=False),
    sa.Column('rule_triggered', sa.String(length=128), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['ai_decisions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_workflow_id'), 'policy_decisions', ['workflow_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('policy_decision_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_type', sa.Enum('RETRY_PAYMENT', 'SEND_PAYMENT_LINK', 'SEND_NOTIFICATION', 'APPLY_INCENTIVE', 'ESCALATE', name='actiontype'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_FLIGHT', 'SUCCEEDED', 'FAILED', 'UNCERTAIN', 'RECONCILED', name='actionstatus'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_actions_workflow_id'), 'actions', ['workflow_id'], unique=False)
    op.create_table('action_attempts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_action_attempts_action_id'), 'action_attempts', ['action_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('rendered_body_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['recovery_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_workflow_id'), 'notifications', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_workflow_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_action_attempts_action_id'), table_name='action_attempts')
    op.drop_table('action_attempts')
    op.drop_index(op.f('ix_actions_workflow_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_policy_decisions_workflow_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_workflow_transitions_workflow_id'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index(op.f('ix_audit_events_workflow_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_decisions_workflow_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_recovery_workflows_merchant_id'), table_name='recovery_workflows')
    op.drop_index(op.f('ix_recovery_workflows_current_state'), table_name='recovery_workflows')
    op.drop_table('recovery_workflows')
    op.drop_index('ix_risk_event_ref', table_name='revenue_risk_events')
    op.drop_index(op.f('ix_revenue_risk_events_merchant_id'), table_name='revenue_risk_events')
    op.drop_index(op.f('ix_revenue_risk_events_customer_id'), table_name='revenue_risk_events')
    op.drop_table('revenue_risk_events')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_evaluation_events_evaluation_run_id'), table_name='evaluation_events')
    op.drop_table('evaluation_events')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
